"""Initial schema

Revision ID: 9a0d7ad75b18
Revises:
Create Date: 2026-08-17 14:56:14.741410

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a0d7ad75b18"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bronze_raw",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("collection_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("request_url", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="bronze",
    )
    op.create_index(
        "idx_bronze_source_timestamp",
        "bronze_raw",
        ["source_name", "collection_timestamp"],
        unique=False,
        schema="bronze",
    )
    op.create_table(
        "chain_linking_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("indicator_id", sa.String(length=100), nullable=False),
        sa.Column("linking_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("base_year_from", sa.Integer(), nullable=False),
        sa.Column("base_year_to", sa.Integer(), nullable=False),
        sa.Column("linking_method", sa.String(length=50), nullable=False),
        sa.Column("records_linked", sa.Integer(), nullable=False),
        sa.Column("avg_confidence_score", sa.Float(), nullable=True),
        sa.Column("overlap_period_months", sa.Integer(), nullable=True),
        sa.Column("growth_rate_variance", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="metadata",
    )
    op.create_index(
        "idx_chain_linking_indicator_timestamp",
        "chain_linking_log",
        ["indicator_id", "linking_timestamp"],
        unique=False,
        schema="metadata",
    )
    op.create_table(
        "data_collection_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("collection_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("records_collected", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("execution_time_seconds", sa.Float(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="metadata",
    )
    op.create_index(
        "idx_collection_source_timestamp",
        "data_collection_log",
        ["source_name", "collection_timestamp"],
        unique=False,
        schema="metadata",
    )
    op.create_table(
        "indicator_catalog",
        sa.Column("indicator_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("domain", sa.String(length=50), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("availability_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("availability_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("has_base_year_changes", sa.Boolean(), nullable=False),
        sa.Column("base_years", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("indicator_id"),
        schema="metadata",
    )
    op.create_index(
        "idx_indicator_domain", "indicator_catalog", ["domain"], unique=False, schema="metadata"
    )
    op.create_index(
        "idx_indicator_source",
        "indicator_catalog",
        ["source_name"],
        unique=False,
        schema="metadata",
    )
    op.create_table(
        "transformation_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_layer", sa.String(length=20), nullable=False),
        sa.Column("target_layer", sa.String(length=20), nullable=False),
        sa.Column("transformation_type", sa.String(length=50), nullable=False),
        sa.Column("transformation_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("records_failed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("execution_time_seconds", sa.Float(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="metadata",
    )
    op.create_index(
        "idx_transformation_layer_timestamp",
        "transformation_log",
        ["target_layer", "transformation_timestamp"],
        unique=False,
        schema="metadata",
    )
    op.create_table(
        "silver_cleaned",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("indicator_id", sa.String(length=100), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("bronze_id", sa.UUID(), nullable=False),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("validation_notes", sa.Text(), nullable=True),
        sa.Column("is_outlier", sa.Boolean(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bronze_id"],
            ["bronze.bronze_raw.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="silver",
    )
    op.create_index(
        "idx_silver_indicator_timestamp",
        "silver_cleaned",
        ["indicator_id", "timestamp"],
        unique=False,
        schema="silver",
    )
    op.create_index(
        "idx_silver_source", "silver_cleaned", ["source_name"], unique=False, schema="silver"
    )
    op.create_table(
        "gold_analytical",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("indicator_id", sa.String(length=100), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("original_value", sa.Float(), nullable=True),
        sa.Column("is_chain_linked", sa.Boolean(), nullable=False),
        sa.Column("chain_linking_confidence", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("domain", sa.String(length=50), nullable=False),
        sa.Column("silver_id", sa.UUID(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["silver_id"],
            ["silver.silver_cleaned.id"],
        ),
        sa.PrimaryKeyConstraint("id", "timestamp"),
        schema="gold",
    )
    op.create_index("idx_gold_domain", "gold_analytical", ["domain"], unique=False, schema="gold")
    op.create_index(
        "idx_gold_indicator_timestamp",
        "gold_analytical",
        ["indicator_id", "timestamp"],
        unique=False,
        schema="gold",
    )
    # ### end Alembic commands ###

    # TimescaleDB setup is not covered by autogenerate. The Gold layer becomes a
    # hypertable partitioned on "timestamp" with monthly chunks, and chunks older
    # than 6 months are compressed.
    op.execute(
        """
        SELECT create_hypertable(
            'gold.gold_analytical',
            'timestamp',
            if_not_exists => TRUE,
            migrate_data => TRUE,
            chunk_time_interval => INTERVAL '1 month'
        );
        """
    )
    op.execute(
        """
        ALTER TABLE gold.gold_analytical
        SET (timescaledb.compress,
             timescaledb.compress_segmentby = 'indicator_id');
        """
    )
    op.execute(
        """
        SELECT add_compression_policy(
            'gold.gold_analytical',
            INTERVAL '6 months',
            if_not_exists => TRUE
        );
        """
    )


def downgrade() -> None:
    # Drop the TimescaleDB policy before the table it references.
    op.execute("SELECT remove_compression_policy('gold.gold_analytical', if_exists => TRUE);")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_gold_indicator_timestamp", table_name="gold_analytical", schema="gold")
    op.drop_index("idx_gold_domain", table_name="gold_analytical", schema="gold")
    op.drop_table("gold_analytical", schema="gold")
    op.drop_index("idx_silver_source", table_name="silver_cleaned", schema="silver")
    op.drop_index("idx_silver_indicator_timestamp", table_name="silver_cleaned", schema="silver")
    op.drop_table("silver_cleaned", schema="silver")
    op.drop_index(
        "idx_transformation_layer_timestamp", table_name="transformation_log", schema="metadata"
    )
    op.drop_table("transformation_log", schema="metadata")
    op.drop_index("idx_indicator_source", table_name="indicator_catalog", schema="metadata")
    op.drop_index("idx_indicator_domain", table_name="indicator_catalog", schema="metadata")
    op.drop_table("indicator_catalog", schema="metadata")
    op.drop_index(
        "idx_collection_source_timestamp", table_name="data_collection_log", schema="metadata"
    )
    op.drop_table("data_collection_log", schema="metadata")
    op.drop_index(
        "idx_chain_linking_indicator_timestamp", table_name="chain_linking_log", schema="metadata"
    )
    op.drop_table("chain_linking_log", schema="metadata")
    op.drop_index("idx_bronze_source_timestamp", table_name="bronze_raw", schema="bronze")
    op.drop_table("bronze_raw", schema="bronze")
    # ### end Alembic commands ###
