"""normalise tgju derived ids

Revision ID: 20c1f356087c
Revises: 90f0451997ef
Create Date: 2026-09-12 12:56:40.279880

One-off data cleanup for the Phase 4 derived-id fix (``src/etl/gold.py``).
Earlier versions double-prefixed already-namespaced source ids, publishing
``TGJU.TGJU.USD.FREE.RET1D`` / ``.MA30`` instead of the documented
``TGJU.USD.FREE.RET1D`` / ``.MA30``. Gold is delete-and-reinsert per indicator,
so the correct ids are regenerated on the next TGJU run; this migration only
removes the orphaned rows so they cannot linger in the dashboard.

``downgrade`` is intentionally a no-op: the deleted rows are derived data that
can be regenerated from Silver on the next pipeline run, not from Gold alone.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20c1f356087c"
down_revision: str | None = "90f0451997ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        sa.text("DELETE FROM gold.gold_analytical WHERE indicator_id LIKE :pattern").bindparams(
            pattern="TGJU.TGJU.%"
        )
    )


def downgrade() -> None:
    # Derived Gold rows are regenerated by re-running the TGJU pipeline.
    pass
