"""Silver unique constraint

Revision ID: 90f0451997ef
Revises: 9a0d7ad75b18
Create Date: 2026-08-19 12:36:58.194186

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90f0451997ef"
down_revision: str | None = "9a0d7ad75b18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_silver_indicator_timestamp",
        "silver_cleaned",
        ["indicator_id", "timestamp"],
        schema="silver",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_silver_indicator_timestamp", "silver_cleaned", schema="silver", type_="unique"
    )
    # ### end Alembic commands ###
